services:
  graphrag-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload

volumes:
  app: