services:
  graphrag-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - GRAPHRAG_LLM_MODEL=llama3
      - LLM_MODEL_API_BASE=http://host.docker.internal:11434/v1
      - GRAPHRAG_EMBEDDING_MODEL=nomic-ai/nomic-embed-text-v1.5-GGUF/nomic-embed-text-v1.5.Q5_K_M.gguf
      - EMBEDDING_MODEL_API_BASE=http://host.docker.internal:1234/v1
      - GRAPHRAG_CLAIM_EXTRACTION_ENABLED=False
      - INPUT_DIR=/app/inputs
      - COMMUNITY_LEVEL=2
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:

  app:


