version: '3.8'

services:
  graphrag-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - GRAPHRAG_LLM_MODEL=llama3
      - LLM_MODEL_API_BASE=http://ollama:11434/v1
      - GRAPHRAG_EMBEDDING_MODEL=nomic-ai/nomic-embed-text-v1.5-GGUF/nomic-embed-text-v1.5.Q5_K_M.gguf
      - EMBEDDING_MODEL_API_BASE=http://ollama:1234/v1
      - GRAPHRAG_CLAIM_EXTRACTION_ENABLED=False
      - INPUT_DIR=/app/inputs
      - COMMUNITY_LEVEL=2
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
      - "1234:1234"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/v1/models" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app: